/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as publicLayoutRouteImport } from './routes/(public)/_layout'
import { Route as publicLayoutSignInRouteImport } from './routes/(public)/_layout/sign-in'
import { Route as publicLayoutSignUpRouteImport } from './routes/(public)/_layout/sign-up'

const publicLayoutRoute = publicLayoutRouteImport.update({
  id: '/(public)/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const publicLayoutSignInRoute = publicLayoutSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => publicLayoutRoute,
} as any)
const publicLayoutSignUpRoute = publicLayoutSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => publicLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/sign-in': typeof publicLayoutSignInRoute
  '/sign-up': typeof publicLayoutSignUpRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof publicLayoutSignInRoute
  '/sign-up': typeof publicLayoutSignUpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(public)/_layout': typeof publicLayoutRouteWithChildren
  '/(public)/_layout/sign-in': typeof publicLayoutSignInRoute
  '/(public)/_layout/sign-up': typeof publicLayoutSignUpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/sign-in' | '/sign-up'
  fileRoutesByTo: FileRoutesByTo
  to: '/sign-in' | '/sign-up'
  id:
    | '__root__'
    | '/(public)/_layout'
    | '/(public)/_layout/sign-in'
    | '/(public)/_layout/sign-up'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  publicLayoutRoute: typeof publicLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(public)/_layout': {
      id: '/(public)/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/_layout/sign-in': {
      id: '/(public)/_layout/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof publicLayoutSignInRouteImport
      parentRoute: typeof publicLayoutRoute
    }
    '/(public)/_layout/sign-up': {
      id: '/(public)/_layout/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof publicLayoutSignUpRouteImport
      parentRoute: typeof publicLayoutRoute
    }
  }
}

interface publicLayoutRouteChildren {
  publicLayoutSignInRoute: typeof publicLayoutSignInRoute
  publicLayoutSignUpRoute: typeof publicLayoutSignUpRoute
}

const publicLayoutRouteChildren: publicLayoutRouteChildren = {
  publicLayoutSignInRoute: publicLayoutSignInRoute,
  publicLayoutSignUpRoute: publicLayoutSignUpRoute,
}

const publicLayoutRouteWithChildren = publicLayoutRoute._addFileChildren(
  publicLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  publicLayoutRoute: publicLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
