/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as publicLayoutRouteImport } from './routes/(public)/_layout'
import { Route as publicLayoutIndexRouteImport } from './routes/(public)/_layout/index'

const publicLayoutRoute = publicLayoutRouteImport.update({
  id: '/(public)/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const publicLayoutIndexRoute = publicLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => publicLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof publicLayoutIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof publicLayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(public)/_layout': typeof publicLayoutRouteWithChildren
  '/(public)/_layout/': typeof publicLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/'
  id: '__root__' | '/(public)/_layout' | '/(public)/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  publicLayoutRoute: typeof publicLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(public)/_layout': {
      id: '/(public)/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/_layout/': {
      id: '/(public)/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicLayoutIndexRouteImport
      parentRoute: typeof publicLayoutRoute
    }
  }
}

interface publicLayoutRouteChildren {
  publicLayoutIndexRoute: typeof publicLayoutIndexRoute
}

const publicLayoutRouteChildren: publicLayoutRouteChildren = {
  publicLayoutIndexRoute: publicLayoutIndexRoute,
}

const publicLayoutRouteWithChildren = publicLayoutRoute._addFileChildren(
  publicLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  publicLayoutRoute: publicLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
