/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as publicLayoutRouteImport } from './routes/(public)/_layout'
import { Route as publicLayoutCadastrarRouteImport } from './routes/(public)/_layout/cadastrar'
import { Route as publicLayoutEntrarRouteImport } from './routes/(public)/_layout/entrar'

const publicLayoutRoute = publicLayoutRouteImport.update({
  id: '/(public)/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const publicLayoutCadastrarRoute = publicLayoutCadastrarRouteImport.update({
  id: '/cadastrar',
  path: '/cadastrar',
  getParentRoute: () => publicLayoutRoute,
} as any)
const publicLayoutEntrarRoute = publicLayoutEntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => publicLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/cadastrar': typeof publicLayoutCadastrarRoute
  '/entrar': typeof publicLayoutEntrarRoute
}
export interface FileRoutesByTo {
  '/cadastrar': typeof publicLayoutCadastrarRoute
  '/entrar': typeof publicLayoutEntrarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(public)/_layout': typeof publicLayoutRouteWithChildren
  '/(public)/_layout/cadastrar': typeof publicLayoutCadastrarRoute
  '/(public)/_layout/entrar': typeof publicLayoutEntrarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/cadastrar' | '/entrar'
  fileRoutesByTo: FileRoutesByTo
  to: '/cadastrar' | '/entrar'
  id:
    | '__root__'
    | '/(public)/_layout'
    | '/(public)/_layout/cadastrar'
    | '/(public)/_layout/entrar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  publicLayoutRoute: typeof publicLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(public)/_layout': {
      id: '/(public)/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/_layout/cadastrar': {
      id: '/(public)/_layout/cadastrar'
      path: '/cadastrar'
      fullPath: '/cadastrar'
      preLoaderRoute: typeof publicLayoutCadastrarRouteImport
      parentRoute: typeof publicLayoutRoute
    }
    '/(public)/_layout/entrar': {
      id: '/(public)/_layout/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof publicLayoutEntrarRouteImport
      parentRoute: typeof publicLayoutRoute
    }
  }
}

interface publicLayoutRouteChildren {
  publicLayoutCadastrarRoute: typeof publicLayoutCadastrarRoute
  publicLayoutEntrarRoute: typeof publicLayoutEntrarRoute
}

const publicLayoutRouteChildren: publicLayoutRouteChildren = {
  publicLayoutCadastrarRoute: publicLayoutCadastrarRoute,
  publicLayoutEntrarRoute: publicLayoutEntrarRoute,
}

const publicLayoutRouteWithChildren = publicLayoutRoute._addFileChildren(
  publicLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  publicLayoutRoute: publicLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
